<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>co.d3vlin</groupId>
  <artifactId>pagila-mapper</artifactId>
  <packaging>jar</packaging>
  <version>1.0.0-SNAPSHOT</version>
  <name>pagila-mapper</name>
  <url>https://github.com/D3vlin</url>
  <properties>
    <maven.compiler.source>21</maven.compiler.source>
    <maven.compiler.target>21</maven.compiler.target>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
    <org.mapstruct.version>1.6.3</org.mapstruct.version>
    <pagila.dto.version>1.0.0-SNAPSHOT</pagila.dto.version>
    <pagila.entity.version>1.0.0-SNAPSHOT</pagila.entity.version>
    <jackson.core.version>3.1.4</jackson.core.version>
  </properties>
  <repositories>
    <repository>
      <id>pagila-dto</id>
      <url>https://maven.pkg.github.com/d3vlin/pagila-dto</url>
    </repository>
    <repository>
      <id>pagila-entity</id>
      <url>https://maven.pkg.github.com/d3vlin/pagila-entity</url>
    </repository>
  </repositories>
  <dependencies>
    <dependency>
      <groupId>org.springframework</groupId>
      <artifactId>spring-context</artifactId>
      <version>7.0.7</version>
    </dependency>
    <dependency>
      <groupId>tools.jackson.core</groupId>
      <artifactId>jackson-core</artifactId>
      <version>${jackson.core.version}</version>
    </dependency>
    <dependency>
      <groupId>${project.groupId}</groupId>
      <artifactId>pagila-dto</artifactId>
      <version>${pagila.dto.version}</version>
    </dependency>
    <dependency>
      <groupId>${project.groupId}</groupId>
      <artifactId>pagila-entity</artifactId>
      <version>${pagila.entity.version}</version>
    </dependency>
    <dependency>
      <groupId>org.mapstruct</groupId>
      <artifactId>mapstruct</artifactId>
      <version>${org.mapstruct.version}</version>
    </dependency>
  </dependencies>
  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.14.1</version>
        <configuration>
          <annotationProcessorPaths>
            <path>
              <groupId>org.mapstruct</groupId>
              <artifactId>mapstruct-processor</artifactId>
              <version>${org.mapstruct.version}</version>
            </path>
          </annotationProcessorPaths>
        </configuration>
      </plugin>
    </plugins>
  </build>
  <distributionManagement>
    <repository>
      <id>pagila</id>
      <url>https://maven.pkg.github.com/d3vlin/pagila-mapper</url>
      <releases>
        <enabled>true</enabled>
      </releases>
      <snapshots>
        <enabled>false</enabled>
      </snapshots>
    </repository>
    <snapshotRepository>
      <id>pagila</id>
      <url>https://maven.pkg.github.com/d3vlin/pagila-mapper</url>
      <releases>
        <enabled>false</enabled>
      </releases>
      <snapshots>
        <enabled>true</enabled>
      </snapshots>
    </snapshotRepository>
  </distributionManagement>
</project>